### ISSUE TITLE
Rework the content for more efficient delivery...

### ISSUE THREAD

**Issue by chalmerlowe** [chalmerlowe/intro_to_sprinting#67]
MAJOR REWORK:

We are gonna revise all the content from top to bottom to fit a new delivery model and template based loosely on this layout:

# For each lesson:

Title

* Short Intro
* Objectives
* Hands-on steps       <<< this is the crux of this approach.
* Detailed explanation of each step
* Resources to learn more

# Why this change?

It takes too long to get students to the last lesson of the day: the lesson where we give them free reign to contribute to a software package based on a calculator.

We spend too much time talking about each step, each instruction, answering off-topic questions, sometimes diving too deeply into topics to the detriment of getting them to the place where they can actually practice the steps, etc. 

This approach allows us to deliver the content in a way that focuses more on getting their system set up fast and easy AND control the amount of time spent on each lesson:

For example:

## OLD WAY:
1. talk about topic...
1. answer questions (sometimes questions that deviate from the topic OR that dive too deeply into the minutiae)
1. talk about topic until the explanation has been completed.
1. execute the command line steps waiting until everyone is complete
1. mentors help those who struggle >> but those folks then fall behind on the next explanation

## NEW WAY:
1. execute the command line steps
1. talk about the topic WHILE mentors help those who struggle
1. answer questions
1. talk about the topic
1. move on at a SET TIME (regardless of whether the full explanation has been completed >> the full explanation is in the write-up with resources to learn more)

## Advantages:

* The mentors can get started sooner on helping folks resolve issues to help folks keep pace
* The content can be delivered in windows that are better controlled
* IF time runs out before a topic has been fully explored, at least the attendees are at the right place: their virtualenv is set up OR the software is installed OR their repo has been cloned and they can always go back and refresh themselves on the concepts at their leisure.

**Comment by seawolf42** [comment]
Slightly better structure:

1. Title
1. Allocated time (for time-boxing)
1. 1-paragraph intro
1. What to do
1. The Big Picture
1. Deep dive
1. Resources/follow-up (though this *could* be in the deep dive directly)

**Comment by seawolf42** [comment]
# Tasks

* [ ] Break existing pages into 15-minute-ish chunks
  * Page name does not include number, just meaningful title (see TOC task for ordering)
  * Tentative break-points:
    * [ ] Environment installation/setup (55m)
      * [ ] Installing tools (conda, git, etc) (10-15m)
      * [ ] Setting up virtual environments (10-15m)
      * [ ] Intro to GitHub and create an account (5-10m)
      * [ ] Fork a repo (5-10m)
      * [ ] Intro to command line (5m)
      * [ ] Introduce self to git (5m)
    * [ ] Git (55m)
      * [ ] Overview/concepts (10-15m)
      * [ ] Clone project (5m)
      * [ ] Add/commit/push (10-15m)
      * [ ] Branch/merge (10-15m)
      * [ ] Merge conflicts (not yet written, but should be 5-10m, can be left out for now)
    * [ ] GitHub p2 (45m)
      * [ ] Review fork/pull/pull request concepts (10-15m)
      * [ ] Sync with upstream and submit PR (10-15m)
      * [ ] Discuss why PR from branch instead of master (10-15m, also not yet written)
    * [ ] Deux it (1 hr)
      * [ ] RPN calc overview (10m)
      * [ ] Do the doing
* Create page templates
  * Each of item in the template structure is an H2 except the title, which is an H1. That way all page headings are consistent. Deep dive might have H3s and H4s if appropriate.
  * [ ] Create template with the following structure for section pages
    * Title
    * Allocated time
    * Short/2-3 paragraph overview
  * [ ] Create template with the following structure for lesson pages
    * Title
    * Allocated time (for time-boxing)
    * Short/1-paragraph intro
    * What to do/hands-on steps       <<< this is the crux of this approach
    * The Big Picture
    * Deep dive/detailed explanation of each step
    * Resources/more reading
* [ ] Put each page from hierarchy in first task into appropriate template
* [ ] Create a table of contents page
  * This page is hierarchical list linking to each of the section and lesson pages
* [ ] Add bottom nav to each page
  * Basic MD table with prev on the left and next on the right

**Comment by chalmerlowe** [comment]
In large measure, the majority of these items have been completed satisfactorily. If additional items remain, they will be opened as individual Issues.
